version: '3'
services:
  inginious-wsgi:
    image: inginious-base:latest
    ports:
      - 0.0.0.0:8080:8080
    volumes:
      - ./container_files/inginious:/inginious
    stdin_open: true
    tty: true
  inginious-backend:
    image: inginious-backend:latest
#  inginious-agent-docker:
#    image: inginious-agent-docker:latest
#    volumes:
#      # This will require an NFS mount.
#      - ./container_root/tasks:/inginious/tasks
#      - /var/run/docker.sock:/var/run/docker.sock
#    stdin_open: true
#    tty: true
#    privileged: true
  inginious-mongodb:
    image: mongo:3.4
    volumes:
      - ./container_files/mongo:/data/db
